### PR TITLE
Update for EAP 6.2.0 ER2

### PR DESCRIPTION
**Pull request by gaol**
This is update according to EAP 6.2.0 ER2 BOM. 

I noticed some versions are even higher than current EAP BOM:

<version.org.hibernate3>3.6.10.Final</version.org.hibernate3>
// the hibernate3 version is higher than current BOM, if you think it should be this way, I will change it back.

<version.org.picketlink>2.5.2.Final</version.org.picketlink> 
// this one has not been merged yet, should be updated for ER3

### CODE REVIEW

**Comment by sgilda** [comment]
@gaol : 
Have you tested this update against the quickstarts located here: https://github.com/jboss-developer/jboss-eap-quickstarts? Please clone that repository, the nconfigure Maven following the instructions here: https://github.com/jboss-developer/jboss-eap-quickstarts/blob/master/README.md#configure-maven

Next install your BOM changess, navigate to the quickstarts located in the above repository and run 'mvn clean install -Pdefault,!complex-dependencies' to verify that they work.

Thanks!

**Comment by sgilda** [comment]
@gaol : To be more clear, the EAP quickstart are now taken from the above Github location and you must be able to build them using only the Maven librabries listed in the `settings.xml` file. The http://jboss-developer.github.io/temp-maven-repo/ repository can be used as a staging repository during development to test new BOMs.

**Comment by rafabene** [comment]
I was not able to find some dependencies on http://maven.repository.redhat.com/ so I can't merge this PR yet

**Comment by pmuir** [comment]
We need to ensure that the quickstarts can be built by anyone, even in development. This helps us get feedback and contributions from external contributors.

**Comment by gaol** [comment]
Close it since it does not satisfy the requirement of quickstarts

**Pull request closed without merging**
