### PR TITLE
JDF-211 Arquillian Drone updated to 1.1.1.Final

### PR DESCRIPTION
**Pull request by kpiwko**

### CODE REVIEW

**Comment by pmuir** [comment]
@kpiwko have you tested this with the quickstarts?

**Comment by kpiwko** [comment]
Not yet. Actually, have you tested 1.0.5.CR1 with quickstarts? I can't run it due to missing deps:

The project org.jboss.as.quickstarts:jboss-as-ejb-security-interceptors:7.1.2-SNAPSHOT (/home/kpiwko/devel/wfk/sandbox/wfk-2.2/jdf/jboss-as-quickstart/ejb-security-interceptors/pom.xml) has 7 errors
[ERROR]     Non-resolvable import POM: Could not find artifact org.jboss.as:jboss-as-ejb-client-bom:pom:7.2.0.Alpha1-SNAPSHOT @ line 82, column 22 -> [Help 2]
[ERROR]     'dependencies.dependency.version' for org.jboss.as:jboss-as-security:jar is missing. @ line 94, column 19
[ERROR]     'dependencies.dependency.version' for org.jboss.ejb3:jboss-ejb3-ext-api:jar is missing. @ line 125, column 19
[ERROR]     'dependencies.dependency.version' for org.jboss:jboss-ejb-client:jar is missing. @ line 132, column 19
[ERROR]     'dependencies.dependency.version' for org.jboss.xnio:xnio-api:jar is missing. @ line 138, column 19
[ERROR]     'dependencies.dependency.version' for org.jboss.xnio:xnio-nio:jar is missing. @ line 144, column 19
[ERROR]     'dependencies.dependency.version' for org.jboss.marshalling:jboss-marshalling-river:jar is missing. @ line 151, column 19
[ERROR]  
[ERROR]   The project org.jboss.as.quickstarts:jboss-as-kitchensink-html5-mobile:7.1.2-SNAPSHOT (/home/kpiwko/devel/wfk/sandbox/wfk-2.2/jdf/jboss-as-quickstart/kitchensink-html5-mobile/pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for org.jboss.as:jboss-as-arquillian-container-managed:jar is missing. @ line 372, column 29

**Comment by pmuir** [comment]
@rafabene ^^^

**Comment by rafabene** [comment]
I have the same issues here. I think that we are waiting for Shelly's repo to finally remove this SNAPSHOTS versions. @pmuir  do you have any news about this subject ?

**Comment by sgilda** [comment]
The ejb-security-interceptors quickstart does not run against Maven central. It requires that you build jboss-as-7.2.0.Alpha1-SNAPSHOT from source, which builds the Maven repository needed for this quickstart. Last time I tried it, it worked fine.

**Comment by kpiwko** [comment]
I disabled ejb-security-interceptors and then applied workarounds for JDF-212, JDF-213, JDF-214 (disabling the quickstart modules until fixed) and JDF-215 as well to enable Arquillian AS7 managed profile.

Than it all passed except of:

 Failed tests: 
  test(org.jboss.as.quickstarts.jaxrsclient.JaxRsClientTest)

which was expected due to fact this test is not automated.

None of the filled issues was Drone 1.1.1.Final related. You guys need a dedicated QE team :-)

**Pull request merged**
