### PR TITLE
EAP7-697 & EAP7-696 upgrade Arquillian and Shrinkwrap resolver versions.

### PR DESCRIPTION
**Pull request by tremes**

### CODE REVIEW

**Comment by kabir** [comment]
@tremes This has conflicts

**Comment by tremes** [comment]
@kabir Updated.

**Comment by tremes** [comment]
I am just wondering who manages these boms. This current snapshot has `<version.org.jboss.eap>7.1.0.Beta1-redhat-3</version.org.jboss.eap>` but the latest EAP maven repository has obviously only `7.1.0.Beta1-redhat-4`.

**Comment by kabir** [comment]
@ctomc and @psakar are in charge. I know little about these

**Pull request merged**
