### PR TITLE
JDF-87 Improved Arquillian With Tools readme file

### PR DESCRIPTION
**Pull request by kpiwko**

### CODE REVIEW

**Comment by pmuir** [comment]
I _think_ that the READMEs are being deprecated in favor of online info on jboss.org/jdf, so I'll let @rafabene handle this pull.

**Comment by kpiwko** [comment]
Pete, what's the proper way how to send a "pull request" against http://www.jboss.org/jdf/stack/jboss-bom/jboss-javaee-6.0-with-tools/ ? Seems to be generated using awestruct from original README.md.

**Comment by pmuir** [comment]
Karel, for the current site, it is the correct way. Rafael is working on a new version of the stacks stuff (see http://site-jdf.rhcloud.com/stack/stacks/ for a preview), which is different. He's still finishing that up, so I don't want to apply this and muck up stuff he's already done.

**Comment by rafabene** [comment]
I'll accept this pull request to get the README.md right :)

**Pull request merged**
